name: Firmware build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
      

permissions:
  contents: read

jobs:
  # Builds with DFU_UPDATE_BUILD=1        
  build_dfu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: make AMILOOP_MINIMAL
      env:
        TRAVIS: 1
        RELEASE: 1
        # DFU_UPDATE_BUILD: 1
        BOARD: AMILOOP_MINIMAL
      run: |
        source ./scripts/provision.sh AMILOOP_MINIMAL
        make  
    - name: Upload AMILOOP_MINIMAL build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: AMILOOP_MINIMAL
        path: |
          bin/*.bin
          bin/*.hex
          bin/*.tgz
          bin/*.zip
